carapace-server/src/main/java/org/carapaceproxy/EndpointMapper.java
carapace-server/src/main/java/org/carapaceproxy/api/ActionsResource.java
carapace-server/src/main/java/org/carapaceproxy/api/ApplicationConfig.java
carapace-server/src/main/java/org/carapaceproxy/api/DirectorsResource.java
carapace-server/src/main/java/org/carapaceproxy/api/MetricsResource.java
carapace-server/src/main/java/org/carapaceproxy/api/RoutesResource.java
carapace-server/src/main/java/org/carapaceproxy/launcher/ServerMain.java
carapace-server/src/main/java/org/carapaceproxy/server/HttpProxyServer.java
carapace-server/src/main/java/org/carapaceproxy/server/backends/BackendHealthManager.java
carapace-server/src/main/java/org/carapaceproxy/server/certiticates/DynamicCertificatesManager.java
carapace-server/src/main/java/org/carapaceproxy/server/config/MatchAllRequestMatcher.java
carapace-server/src/main/java/org/carapaceproxy/server/config/RequestMatcher.java
carapace-server/src/main/java/org/carapaceproxy/server/config/URIRequestMatcher.java
carapace-server/src/main/java/org/carapaceproxy/server/mapper/StandardEndpointMapper.java
carapace-server/src/main/resources/conf/server.properties
carapace-server/src/test/java/org/carapaceproxy/api/StartAPIServerTest.java
carapace-server/src/test/java/org/carapaceproxy/utils/TestEndpointMapper.java
carapace-ui/src/main/webapp/src/App.vue
carapace-ui/src/main/webapp/src/components/Actions.vue
carapace-ui/src/main/webapp/src/components/Backends.vue
carapace-ui/src/main/webapp/src/components/Certificate.vue
carapace-ui/src/main/webapp/src/components/CertificatesStatus.vue
carapace-ui/src/main/webapp/src/components/Directors.vue
carapace-ui/src/main/webapp/src/components/ListenersStatus.vue
carapace-ui/src/main/webapp/src/components/Metrics.vue
carapace-ui/src/main/webapp/src/components/Routes.vue
carapace-ui/src/main/webapp/src/main.js
carapace-ui/src/main/webapp/src/router.js

Views (+ REST API requests) integrated:
- Routes
- Actions
- Directors
- Metrics

Enable the user to see the current configuration from the UI

---

carapace-server/src/main/java/org/carapaceproxy/server/RuntimeServerConfiguration.java
carapace-server/src/main/java/org/carapaceproxy/server/backends/BackendHealthManager.java
carapace-server/src/main/java/org/carapaceproxy/server/certiticates/DynamicCertificatesManager.java
carapace-server/src/test/java/org/carapaceproxy/server/ManagersExecutionTest.java

Bug: backends health probes seems not working with db configuration

---

carapace-server/pom.xml
carapace-server/src/main/java/org/carapaceproxy/cluster/GroupMembershipHandler.java
carapace-server/src/main/java/org/carapaceproxy/cluster/impl/NullGroupMembershipHandler.java
carapace-server/src/main/java/org/carapaceproxy/cluster/impl/ZooKeeperGroupMembershipHandler.java
carapace-server/src/main/java/org/carapaceproxy/server/HttpProxyServer.java
carapace-server/src/test/java/org/carapaceproxy/cluster/impl/ZooKeeperGroupMembershipHandlerTest.java
pom.xml

Introduce GroupMembershipHandler
Introduce first implementation with ZooKeeper
Introduce mode=cluster|standalone
relates to #42

Introduce ZooKeeper based group membership

---

carapace-server/src/main/java/org/carapaceproxy/launcher/ZooKeeperMainWrapper.java
carapace-server/src/main/resources/bin/service
carapace-server/src/main/resources/conf/cluster.properties
carapace-server/src/main/resources/conf/zoo.cfg

- add ZooKeeper server for manual testing (bin/server zookeeper start) (ported from HerdDB)
- add sample zoo.cfg
- add sample cluster configuration
```
bin/service zookeeper start
bin/service server start conf/cluster.properties
```

Add sample ZooKeeper server wrapper

---

carapace-server/src/main/java/org/carapaceproxy/configstore/ConfigurationStore.java
carapace-server/src/main/java/org/carapaceproxy/configstore/HerdDBConfigurationStore.java
carapace-server/src/main/java/org/carapaceproxy/configstore/PropertiesConfigurationStore.java
carapace-server/src/main/java/org/carapaceproxy/server/HttpProxyServer.java
carapace-server/src/main/java/org/carapaceproxy/server/RuntimeServerConfiguration.java
carapace-server/src/main/resources/conf/cluster.properties

Reload configuration from database while receiving a "configuration change event"

Reload configuration from database on other peers

---

carapace-server/src/main/java/org/carapaceproxy/api/CertificatesResource.java
carapace-server/src/main/java/org/carapaceproxy/server/certiticates/DynamicCertificatesManager.java
carapace-server/src/test/java/org/carapaceproxy/api/StartAPIServerTest.java
carapace-ui/src/main/webapp/package-lock.json
carapace-ui/src/main/webapp/package.json
carapace-ui/src/main/webapp/src/components/Certificate.vue

- For Dynamic certificates now it's possible to download the .p12 keystore cert file.
- Fixed NPM'dependencies version

UI: ability to download RAW certificates for dynamic certificates #21

---

run.sh

run.sh was broken.. i've just fixed it

Versioning: update bump version to 1.0.0-SNAPSHOT

---

carapace-server/src/main/java/org/carapaceproxy/server/HttpProxyServer.java
carapace-server/src/main/java/org/carapaceproxy/server/RuntimeServerConfiguration.java
carapace-server/src/main/resources/conf/server.properties
carapace-server/src/test/java/org/carapaceproxy/ApplyConfigurationTest.java
carapace-server/src/test/java/org/carapaceproxy/api/StartAPIServerTest.java

Now userrealm class is loaded at boot as "static configuration"

Auth not working in database mode

---

carapace-server/src/main/java/org/carapaceproxy/cluster/impl/ZooKeeperGroupMembershipHandler.java

Fixed NPE in zookeeper events management

---

pom.xml

#127 Dependences: update HerdDB to latest version

---

pom.xml

Add some info to pom for release:
* license
* scm
* contributors

Add licenses and scm information to pom.xml #126

---

carapace-ui/src/main/webapp/package.json
carapace-ui/src/main/webapp/public/index.html
carapace-ui/src/main/webapp/src/App.vue
carapace-ui/src/main/webapp/src/app.scss
carapace-ui/src/main/webapp/src/components/Actions.vue
carapace-ui/src/main/webapp/src/components/Backends.vue
carapace-ui/src/main/webapp/src/components/CacheStatus.vue
carapace-ui/src/main/webapp/src/components/Certificate.vue
carapace-ui/src/main/webapp/src/components/CertificatesStatus.vue
carapace-ui/src/main/webapp/src/components/Configuration.vue
carapace-ui/src/main/webapp/src/components/DatatableList.vue
carapace-ui/src/main/webapp/src/components/Directors.vue
carapace-ui/src/main/webapp/src/components/Headers.vue
carapace-ui/src/main/webapp/src/components/ListenersStatus.vue
carapace-ui/src/main/webapp/src/components/Metrics.vue
carapace-ui/src/main/webapp/src/components/Peers.vue
carapace-ui/src/main/webapp/src/components/RequestFiltersStatus.vue
carapace-ui/src/main/webapp/src/components/Routes.vue
carapace-ui/src/main/webapp/src/components/Sidebar.vue
carapace-ui/src/main/webapp/src/components/UserRealmStatus.vue
carapace-ui/src/main/webapp/src/lib/formatter.js
carapace-ui/src/main/webapp/src/main.js
carapace-ui/src/main/webapp/src/mockserver.js
carapace-ui/src/main/webapp/src/variables.scss
carapace-ui/src/main/webapp/yarn.lock

- new sidebar
- move tables to bootstrap-vue ones (featuring pagination, columns sorting etc)
- other minor ui bootstrap-vue improves

UI: Improve ui with boostrap-vue #116

---

carapace-ui/src/main/webapp/src/components/CacheStatus.vue
carapace-ui/src/main/webapp/src/components/DatatableList.vue
carapace-ui/src/main/webapp/src/components/Sidebar.vue

Minor changes/fix missed in #147

Feature/#116 bootstrap-vue integration last nit

---

carapace-ui/src/main/webapp/package.json
carapace-ui/src/main/webapp/yarn.lock
pom.xml

Upgrade:
- Netty
- ZooKeeper
- JS Dependencies
- Test dependencies (mockito ,powermock...)
- SLF4J

Upgrade all depdencies

---

carapace-server/src/main/java/org/carapaceproxy/api/ListenersResource.java
carapace-server/src/main/java/org/carapaceproxy/server/Listeners.java
carapace-server/src/main/java/org/carapaceproxy/server/RuntimeServerConfiguration.java
carapace-server/src/main/java/org/carapaceproxy/server/config/NetworkListenerConfiguration.java
carapace-server/src/test/java/org/carapaceproxy/ApplyConfigurationTest.java
carapace-server/src/test/java/org/carapaceproxy/SimpleHTTPProxyTest.java
carapace-server/src/test/java/org/carapaceproxy/listeners/SSLSNITest.java
carapace-server/src/test/java/org/carapaceproxy/server/cache/CacheTest.java
carapace-server/src/test/java/org/carapaceproxy/utils/RawHttpClient.java
carapace-server/src/test/java/org/carapaceproxy/utils/TestUtils.java
carapace-ui/src/main/webapp/src/components/ListenersStatus.vue

New Listener property:
**listener.x.sslprotocols**=comma_separated_list_of_protocols
Default: **_TLSv1.2, TLSv1.3_**

TLS : Ability to Configure which TLS protocol use #160

---

carapace-server/src/main/java/org/carapaceproxy/api/ListenersResource.java
carapace-server/src/main/java/org/carapaceproxy/server/Listeners.java
carapace-server/src/main/java/org/carapaceproxy/server/RequestHandler.java
carapace-server/src/main/java/org/carapaceproxy/server/RuntimeServerConfiguration.java
carapace-server/src/main/java/org/carapaceproxy/server/backends/BackendHealthManager.java
carapace-server/src/main/java/org/carapaceproxy/server/config/NetworkListenerConfiguration.java
carapace-server/src/main/resources/conf/server.dynamic.properties
carapace-server/src/test/java/org/carapaceproxy/api/ConfigResourceTest.java
carapace-server/src/test/java/org/carapaceproxy/server/certificates/CertificatesTest.java
carapace-ui/src/main/webapp/src/components/ListenersStatus.vue
carapace-ui/src/main/webapp/src/mockserver.js

- no more spammy-logs
- tls default protocols (1.2, 1.3) set only with ssl enabled
- fixed "ocps" to "ocsp"

Pre-release 1.3 fixes

---

carapace-server/src/main/java/org/carapaceproxy/server/ClientConnectionHandler.java
carapace-server/src/main/java/org/carapaceproxy/server/RequestsLogger.java
carapace-server/src/main/resources/conf/server.dynamic.properties

Access Log: add TLSversion info for clients requests

---

carapace-server/src/test/java/org/carapaceproxy/api/ConfigResourceTest.java
carapace-server/src/test/java/org/carapaceproxy/server/cache/CaffeineCacheImplTest.java
carapace-server/src/test/java/org/carapaceproxy/utils/TestUtils.java

use Unsafe to set final field values

Make tests pass on JDK12+ use Unsafe

---

.gitignore
carapace-server/pom.xml
carapace-server/src/main/java/org/carapaceproxy/configstore/ConfigurationStore.java
carapace-server/src/main/java/org/carapaceproxy/configstore/ConfigurationStoreUtils.java
carapace-server/src/main/java/org/carapaceproxy/server/HttpProxyServer.java
carapace-server/src/main/java/org/carapaceproxy/server/RuntimeServerConfiguration.java
carapace-server/src/main/java/org/carapaceproxy/server/mapper/StandardEndpointMapper.java
carapace-server/src/main/java/org/carapaceproxy/user/FileUserRealm.java
carapace-server/src/test/java/org/carapaceproxy/configstore/ConfigurationStoreTest.java

Improved configuration reading by adding:
- trimming of values
- standard arrays values formatting (comma separated list of values: e1, e2, e3)
- defaulting for empty values

Configurations > Improvement in carapace configuration #199

---

carapace-server/src/main/java/org/carapaceproxy/api/CertificatesResource.java
carapace-server/src/main/java/org/carapaceproxy/server/certificates/DynamicCertificatesManager.java
carapace-server/src/test/java/org/carapaceproxy/api/StartAPIServerTest.java
carapace-ui/src/main/webapp/src/components/Certificate.vue
carapace-ui/src/main/webapp/src/components/CertificatesStatus.vue

Added Serial Number for all dynamic certificates (acme + manual) in HEX format in UI for:
- Certificates list
- Certificate detail

UI > Show Certificate serial number #202

---

pom.xml

Upgraded:
- Netty
- Netty SSL
- UI dependencies

Libs upgrade

---

carapace-ui/src/main/webapp/package.json
carapace-ui/src/main/webapp/yarn.lock

Upgrade for all libs except for those backward incompatible

UI libs upgrade

---

carapace-ui/src/main/webapp/src/components/DatatableList.vue

Added "all" option for datatables paginator to show all results.

UI - support pagination configuration (10, 25, all) #182

---

carapace-server/src/main/java/org/carapaceproxy/server/RequestHandler.java

NPE releasing closed connection from IdleStateHandler

---

carapace-server/src/main/java/org/carapaceproxy/client/impl/ConnectionsManagerImpl.java
carapace-server/src/main/java/org/carapaceproxy/client/impl/EndpointConnectionImpl.java
carapace-server/src/main/java/org/carapaceproxy/server/RequestHandler.java
carapace-server/src/main/java/org/carapaceproxy/server/RuntimeServerConfiguration.java
carapace-server/src/main/java/org/carapaceproxy/utils/CarapaceLogger.java
carapace-server/src/test/java/org/carapaceproxy/RawClientTest.java

Added a centralized logger (CarapaceLogger) for debug logging.
Added some debug logs for keep tracking connections lifecycle.

Logs for connection lifecycle debug

---

carapace-server/src/main/java/org/carapaceproxy/server/ClientConnectionHandler.java
carapace-server/src/main/java/org/carapaceproxy/server/Listeners.java
carapace-server/src/main/java/org/carapaceproxy/server/RequestHandler.java
carapace-server/src/main/java/org/carapaceproxy/server/RuntimeServerConfiguration.java

Try to not reuse connections for multiple requests

Close connections after backend response

---

carapace-server/src/main/java/org/carapaceproxy/server/ClientConnectionHandler.java
carapace-server/src/main/java/org/carapaceproxy/server/Listeners.java
carapace-server/src/main/java/org/carapaceproxy/server/RuntimeServerConfiguration.java
carapace-server/src/test/java/org/carapaceproxy/RawClientTest.java

New config property for clients idle timeout: _**clients.idle.timeout**_

Configuration property for clients idle timeout

---

carapace-server/src/main/java/org/carapaceproxy/server/cache/ContentsCache.java
carapace-server/src/test/java/org/carapaceproxy/RawClientTest.java
carapace-server/src/test/java/org/carapaceproxy/server/cache/CacheTest.java

Cache control now manages:
- cache-control: private
- cache-control: no-cache
- cache-control: no-store
- cache-control: max-age=0
- cache-control: no-cache, no store, etc
Now headers values check is case insensitive

Bug caching no-cache and no-store

---

carapace-server/src/main/java/org/carapaceproxy/api/CertificatesResource.java
carapace-server/src/main/java/org/carapaceproxy/configstore/CertificateData.java
carapace-server/src/main/java/org/carapaceproxy/configstore/HerdDBConfigurationStore.java
carapace-server/src/main/java/org/carapaceproxy/server/certificates/DynamicCertificatesManager.java
carapace-server/src/test/java/org/carapaceproxy/api/StartAPIServerTest.java
carapace-server/src/test/java/org/carapaceproxy/configstore/ConfigurationStoreTest.java
carapace-server/src/test/java/org/carapaceproxy/server/certificates/CertificatesTest.java
carapace-server/src/test/java/org/carapaceproxy/server/certificates/CertificatesUtilsTest.java
carapace-server/src/test/java/org/carapaceproxy/server/certificates/DynamicCertificatesManagerTest.java

PR for #251 
Changelog:
- empty certificates chains will fallback to default certificate
- removed "available" flag for dynamic certificates

Web page doesn't work in HTTPS during certificate renewal #251

---

carapace-server/src/main/java/org/carapaceproxy/server/certificates/DynamicCertificatesManager.java
carapace-server/src/test/java/org/carapaceproxy/server/certificates/DynamicCertificatesManagerTest.java

IP check has not to be performed for wildcard certificates

Perform dns check before create/renew certificate #239

---

.github/workflows/pr-validation.yml
carapace-server/src/test/java/org/carapaceproxy/ConnectionPoolTest.java
carapace-server/src/test/java/org/carapaceproxy/RawClientTest.java

Updated JKD used in git actions to jdk-15

Git Actions with JDK 15

---

carapace-server/pom.xml
carapace-server/src/main/java/org/carapaceproxy/EndpointStats.java
carapace-server/src/main/java/org/carapaceproxy/api/BackendsResource.java
carapace-server/src/main/java/org/carapaceproxy/client/EndpointKey.java
carapace-server/src/main/java/org/carapaceproxy/core/HttpProxyServer.java
carapace-server/src/main/java/org/carapaceproxy/core/ProxyRequestsManager.java
carapace-server/src/main/java/org/carapaceproxy/launcher/ServerMain.java
pom.xml

Migrating reactor-netty Micrometer data to Prometheus (at path /micrometrics)

Support for Micrometer metrics to Prometheus

---

carapace-server/src/main/java/org/carapaceproxy/core/Listeners.java
carapace-server/src/main/java/org/carapaceproxy/core/ProxyRequest.java
carapace-server/src/main/java/org/carapaceproxy/core/ProxyRequestsManager.java
carapace-server/src/main/java/org/carapaceproxy/core/RequestsLogger.java
carapace-server/src/test/java/org/carapaceproxy/RawClientTest.java

Last nits for v1.7 release pt2

---

carapace-server/src/main/java/org/carapaceproxy/core/ProxyRequest.java
carapace-server/src/main/java/org/carapaceproxy/core/ProxyRequestsManager.java
carapace-server/src/test/java/org/carapaceproxy/RawClientTest.java
carapace-server/src/test/java/org/carapaceproxy/server/cache/CacheTest.java

Fix duplicated cookies sent from client requests/server responses

Fix to cookies forwarding

---

carapace-server/src/main/java/org/carapaceproxy/core/ProxyRequestsManager.java
carapace-server/src/main/java/org/carapaceproxy/core/StaticContentsManager.java
carapace-server/src/main/java/org/carapaceproxy/server/cache/CaffeineCacheImpl.java
carapace-server/src/main/java/org/carapaceproxy/server/cache/ContentsCache.java
carapace-server/src/test/java/org/carapaceproxy/server/cache/CacheTest.java
pom.xml

Fix direct memory leak

---

.gitignore
carapace-server/src/main/java/org/carapaceproxy/api/ListenersResource.java
carapace-server/src/main/java/org/carapaceproxy/core/HttpProxyServer.java
carapace-server/src/main/java/org/carapaceproxy/core/Listeners.java
carapace-server/src/main/java/org/carapaceproxy/core/RuntimeServerConfiguration.java
carapace-server/src/main/java/org/carapaceproxy/core/TrustStoreManager.java
carapace-server/src/main/java/org/carapaceproxy/server/certificates/ocsp/OcspRequestBuilder.java
carapace-server/src/main/java/org/carapaceproxy/server/certificates/ocsp/OcspStaplingManager.java
carapace-server/src/main/java/org/carapaceproxy/server/certificates/ocsp/OcspUtils.java
carapace-server/src/main/java/org/carapaceproxy/server/config/NetworkListenerConfiguration.java
carapace-server/src/main/java/org/carapaceproxy/utils/CertificatesUtils.java
carapace-server/src/test/java/org/carapaceproxy/RawClientTest.java
carapace-server/src/test/java/org/carapaceproxy/SimpleHTTPProxyTest.java
carapace-server/src/test/java/org/carapaceproxy/listeners/SSLSNITest.java
carapace-server/src/test/java/org/carapaceproxy/server/cache/CacheTest.java
carapace-server/src/test/java/org/carapaceproxy/server/certificates/CertificatesTest.java
carapace-ui/src/main/webapp/src/components/ListenersStatus.vue
carapace-ui/src/main/webapp/src/mockserver.js

OCSP stapling not working

---

carapace-server/src/main/java/org/carapaceproxy/api/RequestFiltersResource.java
carapace-server/src/main/java/org/carapaceproxy/server/filters/RequestFilterFactory.java
carapace-server/src/main/java/org/carapaceproxy/server/filters/XTlsCipherRequestFilter.java
carapace-server/src/main/java/org/carapaceproxy/server/filters/XTlsProtocolRequestFilter.java
carapace-server/src/test/java/org/carapaceproxy/api/StartAPIServerTest.java
carapace-server/src/test/java/org/carapaceproxy/server/filters/XTlsCipherFilterTest.java
carapace-server/src/test/java/org/carapaceproxy/server/filters/XTlsProtocolFilterTest.java
carapace-server/src/test/java/org/carapaceproxy/utils/RawHttpClient.java

Provide new filter for tls protocol and tls cipher.
Usage:
```
filter.x.type=add-x-tls-cipher
filter.x.type=add-x-tls-protocol
```

Add filter for tls protocol and tls cipher

---

.github/workflows/pr-validation.yml
carapace-server/nb-configuration.xml
carapace-server/src/main/resources/bin/setenv.sh
carapace-ui/pom.xml
pom.xml

JDK-17 Support

---

pom.xml

Update reactor netty to 1.0.23

Update reactor netty

---

carapace-ui/src/main/webapp/src/components/certificates/CertificateForm.vue
carapace-ui/src/main/webapp/src/components/certificates/Certificates.vue

#413
Also added the redirect to the certificate page

Add loading in progress in certificate creation form

---

carapace-server/src/main/java/org/carapaceproxy/api/ConnectionPoolsResource.java
carapace-server/src/main/java/org/carapaceproxy/core/HttpProxyServer.java
carapace-server/src/main/java/org/carapaceproxy/core/ProxyRequestsManager.java
carapace-server/src/main/java/org/carapaceproxy/core/RuntimeServerConfiguration.java
carapace-server/src/main/java/org/carapaceproxy/server/config/ConnectionPoolConfiguration.java
carapace-server/src/test/java/org/carapaceproxy/backends/ConnectionPoolTest.java

Introduce maxLifeTime for connection pool

---

carapace-server/src/main/java/org/carapaceproxy/configstore/ConfigurationStore.java
carapace-server/src/main/java/org/carapaceproxy/core/RuntimeServerConfiguration.java
carapace-server/src/main/java/org/carapaceproxy/server/cache/CacheRuntimeConfiguration.java
carapace-server/src/main/java/org/carapaceproxy/server/cache/ContentsCache.java
carapace-server/src/main/resources/conf/server.dynamic.properties

Add support to WebP caching even in case of query string
See #462

Add support to WebP caching

---

carapace-server/src/main/java/org/carapaceproxy/server/mapper/MapResult.java
carapace-server/src/main/java/org/carapaceproxy/server/mapper/StandardEndpointMapper.java
carapace-server/src/test/java/org/carapaceproxy/backends/StuckRequestsTest.java
carapace-server/src/test/java/org/carapaceproxy/server/mapper/BasicStandardEndpointMapperTest.java

Return Service Unavailable 503 when every backend is down

---

carapace-server/src/main/java/org/carapaceproxy/api/ConnectionPoolsResource.java
carapace-server/src/main/java/org/carapaceproxy/core/ForwardedStrategies.java
carapace-server/src/main/java/org/carapaceproxy/core/RuntimeServerConfiguration.java
carapace-server/src/main/java/org/carapaceproxy/server/config/ConnectionPoolConfiguration.java
carapace-server/src/test/java/org/carapaceproxy/core/ForwardedStrategyTest.java

Hotfix 2.0.1

---

.github/workflows/release.yml
pom.xml

ci: wrong hotfix version computed

---

pom.xml

* upgrade Project Reactor Release Train to `2024.0.2`
* upgrade Reactor Netty to `1.2.2`
* upgrade Netty to `4.1.117.Final`

build: upgrade Netty and Reactor Netty

---

carapace-server/src/main/java/org/carapaceproxy/server/mapper/StandardEndpointMapper.java
carapace-server/src/test/java/org/carapaceproxy/RequestSmugglingVulnerabilityTest.java

fix: mitigate CL.0 request smuggling
