diennea/carapaceproxy

carapace-server/pom.xml
See https://github.com/tomakehurst/wiremock/issues/970
=> Upgrade Wiremock and use wiremock-jre8 which supports better jdk11

carapace-server/src/main/java/org/carapaceproxy/MapResult.java, carapace-server/src/main/java/org/carapaceproxy/server/RequestHandler.java, carapace-server/src/main/java/org/carapaceproxy/server/config/ActionConfiguration.java, carapace-server/src/main/java/org/carapaceproxy/server/mapper/CustomHeader.java, carapace-server/src/main/java/org/carapaceproxy/server/mapper/StandardEndpointMapper.java, carapace-server/src/test/java/org/carapaceproxy/server/RequestsLoggerTest.java, carapace-server/src/test/java/org/carapaceproxy/server/mapper/BasicStandardEndpointMapperTest.java, carapace-server/src/test/java/org/carapaceproxy/utils/TestEndpointMapper.java
Now it's possible to define http-response-headers to add/set/remove (default add) for the actions (of any type):
```
action.1.director=director_name
action.1.enabled=true
action.1.id=action_id
action.1.type=cache
action.1.headers=h1,h2
/* custom headers */
header.id=h1
header.name=Strict-Transport-Security
header.mode= remove
header.id=h2
header.name=MyHeader
header.value=MyHeaderValue
header.mode=add | set
```
=> Add possibility to insert header between the actions #46

carapace-server/src/main/java/org/carapaceproxy/api/ApplicationConfig.java, carapace-server/src/main/java/org/carapaceproxy/api/ClusterResource.java, carapace-server/src/main/java/org/carapaceproxy/cluster/GroupMembershipHandler.java, carapace-server/src/main/java/org/carapaceproxy/cluster/impl/NullGroupMembershipHandler.java, carapace-server/src/main/java/org/carapaceproxy/cluster/impl/ZooKeeperGroupMembershipHandler.java, carapace-server/src/main/java/org/carapaceproxy/server/HttpProxyServer.java, carapace-server/src/test/java/org/carapaceproxy/cluster/impl/ZooKeeperGroupMembershipHandlerTest.java, carapace-ui/pom.xml, carapace-ui/src/main/webapp/public/index.html, carapace-ui/src/main/webapp/src/App.vue, carapace-ui/src/main/webapp/src/components/Peers.vue, carapace-ui/src/main/webapp/src/router.js
Improvements:
- UI now has a dedicated section with list of Cluster peers
- API now allows to query peers
- Now it's possible to store and load some properties (Map<String,String> info) for peers
=> UI: list of cluster peers #62

carapace-server/src/main/java/org/carapaceproxy/server/mapper/requestmatcher/AndRequestMatcher.java, carapace-server/src/main/java/org/carapaceproxy/server/mapper/requestmatcher/EqualsRequestMatcher.java, carapace-server/src/main/java/org/carapaceproxy/server/mapper/requestmatcher/MatchAllRequestMatcher.java, carapace-server/src/main/java/org/carapaceproxy/server/mapper/requestmatcher/OrRequestMatcher.java, carapace-server/src/main/java/org/carapaceproxy/server/mapper/requestmatcher/RegexpRequestMatcher.java, carapace-server/src/main/java/org/carapaceproxy/server/mapper/requestmatcher/SecureRequestMatcher.java, carapace-server/src/main/javacc/RequestMatchParser.jj, carapace-server/src/test/java/org/carapaceproxy/server/mapper/requestmatcher/RequestMatcherTest.java
* Description for RegexpMatcher fixed: from *RegExp REGEXP* to *property ~ "REGEXP"*
* Now brackets are shown only when actualy used
=> 77 UI: Fix Request matcher description

carapace-server/src/main/java/org/carapaceproxy/api/BackendsResource.java, carapace-server/src/main/java/org/carapaceproxy/api/ListenersResource.java, carapace-server/src/main/java/org/carapaceproxy/client/EndpointKey.java, carapace-server/src/main/java/org/carapaceproxy/client/impl/ConnectionsManagerImpl.java, carapace-server/src/main/java/org/carapaceproxy/client/impl/EndpointConnectionImpl.java, carapace-server/src/main/java/org/carapaceproxy/server/backends/BackendHealthManager.java, carapace-server/src/main/java/org/carapaceproxy/server/backends/BackendHealthStatus.java, carapace-server/src/main/java/org/carapaceproxy/server/mapper/StandardEndpointMapper.java, carapace-server/src/test/java/org/carapaceproxy/backends/UnreachableBackendTest.java, carapace-server/src/test/java/org/carapaceproxy/server/mapper/HealthCheckTest.java
In StandardEndpoinMapper backendHealthManager.isAvailable() is called with backendId instead of hostname:port as expected by BackendHealthManager.
=> EndpointMapper: Backends availability cheked according to backendid instead of host:port #78

carapace-server/src/main/resources/bin/carapace.service
If you need to configure the service to run at startup, you can use this systemd script.
- edit carapace.service and insert correct "User", "Group" and "installation path"
- copy carapace.service in /etc/systemd/system
- systemctl enable carapace.service 
- systemctl start carapace.service (To start carapace)
- systemctl stop carapace.service (To stop carapace)
- systemctl restart carapace.service (To restart carapace)
=> Add systemd script

carapace-server/pom.xml, carapace-server/src/main/java/org/carapaceproxy/client/EndpointConnection.java, carapace-server/src/main/java/org/carapaceproxy/client/impl/ConnectionsManagerImpl.java, carapace-server/src/main/java/org/carapaceproxy/client/impl/EndpointConnectionImpl.java, carapace-server/src/main/java/org/carapaceproxy/server/ClientConnectionHandler.java, carapace-server/src/main/java/org/carapaceproxy/server/RequestHandler.java, carapace-server/src/main/java/org/carapaceproxy/server/RuntimeServerConfiguration.java, carapace-server/src/main/resources/conf/server.dynamic.properties, carapace-server/src/test/java/org/carapaceproxy/ConnectionPoolTest.java, carapace-server/src/test/java/org/carapaceproxy/RawClientTest.java, carapace-server/src/test/java/org/carapaceproxy/server/cache/CacheExpireTest.java, carapace-server/src/test/java/org/carapaceproxy/server/cache/CacheTest.java, carapace-server/untilfail, pom.xml
Introduce a new configuration parameter: connectionsmanager.borrowtimeout.
We were using connectiontimoeut * 2 to wait for a connection to be available, but waiting for an existing connection is far different from a "Connection timeout".
We are also adding more debug in case of IDLE connection validation, this way we will have more insights about whats happening.
I am also fixing race conditions regarding keep-alive connections observed in Travis
This patch also upgrades commons-pool2 to latest version 2.6.2
Relates #111
=> Introduce Max time to borrow a connection from the pool, not using connecttimeout any more

.travis.yml, carapace-server/src/main/java/org/carapaceproxy/api/CertificatesResource.java, carapace-server/src/main/java/org/carapaceproxy/server/backends/BackendHealthManager.java, carapace-server/src/main/java/org/carapaceproxy/server/certiticates/ACMEClient.java, carapace-server/src/main/java/org/carapaceproxy/server/certiticates/DynamicCertificatesManager.java, carapace-server/src/test/java/org/carapaceproxy/server/certiticates/DynamicCertificatesManagerTest.java
* Added more debug
* Moved to FINE/DEBUG some too verbose INFO logs
* Fixed bug for which WAITING certificates were not saved on db whether AVAILABLE ones were processed before them
* Fixed a NPE in CertificatesResource when trying to stringify the certificate status (status is null as long as the certificate isn't stored to the db, which happens only when the manager successfully process it)
* Now certificates are processed according to the hostname in ascending alphabetically order
=> DynamiCertificateManager: certificate locked at WAITING state

carapace-server/pom.xml, carapace-server/src/main/java/org/carapaceproxy/api/CertificatesResource.java, carapace-server/src/main/java/org/carapaceproxy/api/ConfigResource.java, carapace-server/src/main/java/org/carapaceproxy/configstore/CertificateData.java, carapace-server/src/main/java/org/carapaceproxy/configstore/ConfigurationStore.java, carapace-server/src/main/java/org/carapaceproxy/configstore/ConfigurationStoreUtils.java, carapace-server/src/main/java/org/carapaceproxy/configstore/HerdDBConfigurationStore.java, carapace-server/src/main/java/org/carapaceproxy/server/HttpProxyServer.java, carapace-server/src/main/java/org/carapaceproxy/server/Listeners.java, carapace-server/src/main/java/org/carapaceproxy/server/RuntimeServerConfiguration.java, carapace-server/src/main/java/org/carapaceproxy/server/certiticates/DynamicCertificatesManager.java, carapace-server/src/main/java/org/carapaceproxy/server/config/SSLCertificateConfiguration.java, carapace-server/src/main/java/org/carapaceproxy/utils/CertificatesUtils.java, carapace-server/src/main/resources/conf/server.dynamic.properties, carapace-server/src/test/java/org/carapaceproxy/SimpleHTTPProxyTest.java, carapace-server/src/test/java/org/carapaceproxy/api/StartAPIServerTest.java, carapace-server/src/test/java/org/carapaceproxy/api/UseAdminServer.java, carapace-server/src/test/java/org/carapaceproxy/configstore/ConfigurationStoreTest.java, carapace-server/src/test/java/org/carapaceproxy/configstore/ConfigurationStoreUtilsTest.java, carapace-server/src/test/java/org/carapaceproxy/listeners/SSLSNITest.java, carapace-server/src/test/java/org/carapaceproxy/server/cache/CacheTest.java, carapace-server/src/test/java/org/carapaceproxy/server/certiticates/CertificatesTest.java, carapace-server/src/test/java/org/carapaceproxy/server/certiticates/DynamicCertificatesManagerTest.java, carapace-server/src/test/java/org/carapaceproxy/utils/CertificatesTestUtils.java, carapace-server/src/test/java/org/carapaceproxy/utils/RawHttpClient.java, carapace-ui/src/main/webapp/src/components/Certificate.vue, carapace-ui/src/main/webapp/src/components/CertificatesStatus.vue, pom.xml
New kind of certificate: MANUAL:
* loadble only from api (.p12 file with no pw)
* stored to db but managed by admin (renewal)
ConfigurationStore:
* ability to retrive next available index for a property-name
* check whether a regexp matches with an existing property (key+value)
* get all properties
SSlCertificateConfiguration:
* property sslcertfile renamed to file
* property sslcertfilepassword renamed to password
* property iddynamic removed
* new property mode = acme|static|manual added
Dependecies:
* updated herddb to 0.10.1
Refactoring:
* extract keystore store-load-check methods to CertificateUtils class
=> Certificates: DB management for Static Certificates #76

carapace-server/src/main/java/org/carapaceproxy/client/impl/EndpointConnectionImpl.java
Labels 'host' and 'result' were swapped for metric 'backends_connection_time_ns'. Fixed.
=> #152 Error in backends_connection_time_ns metric

carapace-server/src/main/java/org/carapaceproxy/client/EndpointConnection.java, carapace-server/src/main/java/org/carapaceproxy/client/impl/ConnectionsManagerImpl.java, carapace-server/src/main/java/org/carapaceproxy/client/impl/EndpointConnectionImpl.java, carapace-server/src/main/java/org/carapaceproxy/server/ClientConnectionHandler.java, carapace-server/src/main/java/org/carapaceproxy/server/RequestHandler.java, carapace-server/src/test/java/org/carapaceproxy/ConnectionPoolTest.java, carapace-server/src/test/java/org/carapaceproxy/RawClientTest.java
- ensure that changes to the state of EndpointConnectionImpl happen inside the Endpoint event loop
- track status of writes to the client in RequestHandler (useful for heapdumps)
- release connection to the endpoint as soon as we receive the LastHttpContent from the backend, this saves resource in case of slow or stuck clients (non writable socket to the client)
=> Better EndpointConnection lifecycle handling:

carapace-server/pom.xml, carapace-server/src/main/java/org/carapaceproxy/EndpointMapper.java, carapace-server/src/main/java/org/carapaceproxy/api/CertificatesResource.java, carapace-server/src/main/java/org/carapaceproxy/configstore/CertificateData.java, carapace-server/src/main/java/org/carapaceproxy/configstore/HerdDBConfigurationStore.java, carapace-server/src/main/java/org/carapaceproxy/server/HttpProxyServer.java, carapace-server/src/main/java/org/carapaceproxy/server/RuntimeServerConfiguration.java, carapace-server/src/main/java/org/carapaceproxy/server/certificates/ACMEClient.java, carapace-server/src/main/java/org/carapaceproxy/server/certificates/DynamicCertificateState.java, carapace-server/src/main/java/org/carapaceproxy/server/certificates/DynamicCertificatesManager.java, carapace-server/src/main/java/org/carapaceproxy/server/certificates/DynamicCertificatesManagerException.java, carapace-server/src/main/java/org/carapaceproxy/server/mapper/StandardEndpointMapper.java, carapace-server/src/main/java/org/carapaceproxy/utils/APIUtils.java, carapace-server/src/test/java/org/carapaceproxy/api/StartAPIServerTest.java, carapace-server/src/test/java/org/carapaceproxy/configstore/ConfigurationStoreTest.java, carapace-server/src/test/java/org/carapaceproxy/configstore/ConfigurationStoreUtilsTest.java, carapace-server/src/test/java/org/carapaceproxy/server/ManagersExecutionTest.java, carapace-server/src/test/java/org/carapaceproxy/server/certificates/CertificatesTest.java, carapace-server/src/test/java/org/carapaceproxy/server/certificates/DynamicCertificatesManagerTest.java, carapace-server/src/test/java/org/carapaceproxy/server/mapper/BasicStandardEndpointMapperTest.java, carapace-server/src/test/java/org/carapaceproxy/utils/CertificatesTestUtils.java
Improved API for Certficates management with new optional parameter **type** [manual | acme] (default **_manual_**) for function POST _**api/certificates/{domain}/upload**_:
- use _**acme**_ to create an ACME certificate (automatically managed by Carapace)
- use _**manual**_ to create a MANUAL certificate (manage manually)
**Use cases:**
- To simply add an existing certificate to Carapace just make the request with by POSTing the "certificate-data".
- To create a brand new order for an ACME certificate just call _**api/certificates/{domain}/upload?type=acme**_ with no "certificate-data".
- Updating existing certificate is now available, even convert (switch) from _manual_ to _acme_ and vice versa.
=> API improvements to certificate upload function

carapace-server/src/main/java/org/carapaceproxy/server/ClientConnectionHandler.java
Fix for issue #168 
Increment 'listeners_running_requests' and 'listeners_requests_total' metrics at start of request instead of on LastHttpContent reception.
=> ClientConnectionHandler metrics #168

carapace-server/src/main/java/org/carapaceproxy/EndpointMapper.java, carapace-server/src/main/java/org/carapaceproxy/SimpleHTTPResponse.java, carapace-server/src/main/java/org/carapaceproxy/api/RoutesResource.java, carapace-server/src/main/java/org/carapaceproxy/server/RequestHandler.java, carapace-server/src/main/java/org/carapaceproxy/server/StaticContentsManager.java, carapace-server/src/main/java/org/carapaceproxy/server/config/ActionConfiguration.java, carapace-server/src/main/java/org/carapaceproxy/server/config/RouteConfiguration.java, carapace-server/src/main/java/org/carapaceproxy/server/mapper/StandardEndpointMapper.java, carapace-server/src/main/resources/bin/setenv.sh, carapace-server/src/test/java/org/carapaceproxy/server/mapper/BasicStandardEndpointMapperTest.java, carapace-ui/src/main/webapp/src/components/Routes.vue
- Now it's possible to attach a custom action/message to routes, in order to serve the proper response/code in case of error (see #185).
- Fixed a NPE in response building by static content (now will be return 404 for resources unable to find)
- Added Error-Action column to Routes UI
- Fixed custom headers support for Error Actions
=> Route error messages customization #185

carapace-server/src/main/java/org/carapaceproxy/api/CertificatesResource.java, carapace-server/src/main/java/org/carapaceproxy/configstore/CertificateData.java, carapace-server/src/main/java/org/carapaceproxy/configstore/ConfigurationStoreUtils.java, carapace-server/src/main/java/org/carapaceproxy/server/HttpProxyServer.java, carapace-server/src/main/java/org/carapaceproxy/server/RuntimeServerConfiguration.java, carapace-server/src/main/java/org/carapaceproxy/server/certificates/DynamicCertificatesManager.java, carapace-server/src/main/java/org/carapaceproxy/server/config/SSLCertificateConfiguration.java, carapace-server/src/main/java/org/carapaceproxy/utils/CertificatesUtils.java, carapace-server/src/test/java/org/carapaceproxy/server/certificates/CertificatesTest.java, carapace-server/src/test/java/org/carapaceproxy/server/certificates/CertificatesUtilsTest.java, carapace-server/src/test/java/org/carapaceproxy/server/certificates/DynamicCertificatesManagerTest.java, carapace-ui/src/main/webapp/src/components/Certificate.vue, carapace-ui/src/main/webapp/src/components/CertificatesStatus.vue
Ref #191
- Configuration: new integer property **_certificate.x.daysbeforerenewal_** to set how many days before expiration the certificate has to be renew (**default 30 days**).
- Rest API: new query parameter **_daysbeforerenewal_** for ACME certificates uploading.
- UI added information about **_expiring date_** and the property **_daysbeforerenewal_** set, for ACME Certificates list and detail.
- New system property **_carapace.acme.default.daysbeforerenewal_** to change the default value.
=> Dinamic certs - request the certs before they are expiring #191

carapace-server/src/main/java/org/carapaceproxy/configstore/ConfigurationStore.java, carapace-server/src/main/java/org/carapaceproxy/server/HttpProxyServer.java, carapace-server/src/main/java/org/carapaceproxy/server/RuntimeServerConfiguration.java, carapace-server/src/main/java/org/carapaceproxy/server/mapper/StandardEndpointMapper.java, carapace-server/src/test/java/org/carapaceproxy/configstore/ConfigurationStoreTest.java
In order to manage a greater amount of certificates we need to drop the limit of 100 entries for property index in configuration file.
By this improve, now configuration properties are fetched by iterating from index 0 to the max for that property prefix-name.
=> Configuration entries max size fixed

carapace-server/pom.xml, carapace-server/src/main/java/org/carapaceproxy/api/CertificatesResource.java, carapace-server/src/main/java/org/carapaceproxy/configstore/CertificateData.java, carapace-server/src/main/java/org/carapaceproxy/server/Listeners.java, carapace-server/src/main/java/org/carapaceproxy/server/RuntimeServerConfiguration.java, carapace-server/src/main/java/org/carapaceproxy/server/certificates/ACMEClient.java, carapace-server/src/main/java/org/carapaceproxy/server/certificates/DynamicCertificateState.java, carapace-server/src/main/java/org/carapaceproxy/server/certificates/DynamicCertificatesManager.java, carapace-server/src/main/java/org/carapaceproxy/server/certificates/Route53Client.java, carapace-server/src/main/java/org/carapaceproxy/server/config/SSLCertificateConfiguration.java, carapace-server/src/main/java/org/carapaceproxy/utils/APIUtils.java, carapace-server/src/test/java/org/carapaceproxy/server/certificates/CertificatesTest.java, carapace-server/src/test/java/org/carapaceproxy/server/certificates/DynamicCertificatesManagerTest.java, carapace-server/src/test/java/org/carapaceproxy/server/certificates/Route53ClientTest.java, carapace-ui/src/main/webapp/src/components/Configuration.vue
Now can be ordered wildcard certificates in form of *.mydomain.com by Let's Encrypt CA
=> Let's Encrypt: possibility to order wildcard certificates with Route53 API #188

carapace-server/src/main/java/org/carapaceproxy/server/HttpProxyServer.java, carapace-server/src/main/java/org/carapaceproxy/server/RuntimeServerConfiguration.java, carapace-server/src/main/java/org/carapaceproxy/server/certificates/ACMEClient.java, carapace-server/src/main/java/org/carapaceproxy/server/certificates/DynamicCertificatesManager.java, carapace-server/src/main/resources/conf/cluster.properties, carapace-server/src/main/resources/conf/server.properties, carapace-server/src/test/java/org/carapaceproxy/ApplyConfigurationTest.java, carapace-server/src/test/java/org/carapaceproxy/server/ManagersExecutionTest.java, carapace-server/src/test/java/org/carapaceproxy/server/certificates/CertificatesTest.java, carapace-server/src/test/java/org/carapaceproxy/server/certificates/DynamicCertificatesManagerTest.java
- Now aws secret/access keys has to be set in static configuration
- AcmeExceptions (ex network errors) does not set certificate state to request failed anymore: all previous states stuff are stored on db or cached on Let's Encrypt, so redoing a request from scratch is just a waste of time/resources.
=> Carapace pre-release fixes

.github/issue_template.md, .github/pull_request_template.md, .github/workflows/pr-validation.yml, carapace-server/src/main/java/org/carapaceproxy/client/impl/ConnectionsManagerImpl.java, carapace-server/src/main/java/org/carapaceproxy/client/impl/EndpointConnectionImpl.java, carapace-server/src/main/java/org/carapaceproxy/server/RuntimeServerConfiguration.java, carapace-server/src/test/java/org/carapaceproxy/backends/StuckRequestsTest.java, carapace-server/src/test/java/org/carapaceproxy/backends/UnreachableBackendTest.java
Added a way to avoid the disabling of backends reachability for stacked requests:
> new property connectionsmanager.backendsunreachableonstuckrequests=true|false (default false)
 Raised the timeout for connectFuture
Avoid check+recreation of connections when returned to the pool
=> Connections management improvement

.github/workflows/pr-validation.yml, carapace-server/src/main/java/org/carapaceproxy/client/impl/ConnectionsManagerImpl.java
Now connections releasing and recreation for the pool is done throw a dedicated thread pool instead of netty eventloop.
Sistem-property for threadpool size: _**carapace.connectionsmanager.returnconnectionthreadpool.size**_ (default **10**; 0 for rollback)
=> Netty eventloop deadlock on connections release

carapace-server/src/main/java/org/carapaceproxy/client/EndpointConnection.java, carapace-server/src/main/java/org/carapaceproxy/client/impl/ConnectionsManagerImpl.java, carapace-server/src/main/java/org/carapaceproxy/client/impl/EndpointConnectionImpl.java, carapace-server/src/main/java/org/carapaceproxy/server/RequestHandler.java, carapace-server/src/test/java/org/carapaceproxy/RawClientTest.java
Some fix in order to properly release connections:
- during EndpointConnectionImpl#sendRequest from clients, in case of errorSendingRequest (before starting writing to the server) we need to release the connection immediately or none will do
- when RequestHandler#releaseConnectionToEndpoint is called either by server and client, whether the first one cannot actually release the connection, the second one won't perform the release anymore because of the compareAndSet which set the connection to null even if the release is delayed.
- Added a test case to reproduce the case of a non released connection on errorSendingRequest
=> Fix connections release leaks

carapace-server/src/main/java/org/carapaceproxy/server/ClientConnectionHandler.java, carapace-server/src/main/java/org/carapaceproxy/server/Listeners.java, carapace-server/src/main/java/org/carapaceproxy/server/RequestHandler.java, carapace-server/src/test/java/org/carapaceproxy/server/mapper/requestmatcher/RequestMatcherTest.java
In Route configuration,  it might be useful to separate the traffic based on the ip used to forward the request.
This is because there can be dedicated ip's  for a particular customer.
=> Filter requests based on server ip

carapace-server/src/main/java/org/carapaceproxy/client/impl/ConnectionsManagerImpl.java, carapace-server/src/main/java/org/carapaceproxy/client/impl/EndpointConnectionImpl.java, carapace-server/src/main/java/org/carapaceproxy/server/RuntimeServerConfiguration.java, carapace-server/src/test/java/org/carapaceproxy/RawClientTest.java
Debug header added to keep track of connections id from carapace to endpoints
=> Requests header debug

carapace-server/src/main/java/org/carapaceproxy/api/CertificatesResource.java, carapace-server/src/main/java/org/carapaceproxy/server/Listeners.java, carapace-server/src/main/java/org/carapaceproxy/server/certificates/DynamicCertificatesManager.java, carapace-server/src/main/java/org/carapaceproxy/utils/CertificatesUtils.java, carapace-server/src/test/java/org/carapaceproxy/api/StartAPIServerTest.java, carapace-server/src/test/java/org/carapaceproxy/server/certificates/CertificatesUtilsTest.java, carapace-ui/src/main/webapp/src/components/Certificate.vue
PR for #196
Changelog:
Add additional information in UI for static/manual certificates:
- status (available/expired)
- expiringDate
- serialNumber
=> Certiticates > Add more info for static and manual certificates in UI

carapace-server/pom.xml, carapace-server/src/main/java/org/carapaceproxy/server/HttpProxyServer.java, pom.xml
PR for #225
Changelog:
- HerdDB > 0.22.0
- Netty > 4.1.59.Final
- Netty ssl > 2.0.36
=> Bump HerdDB to 0.22.0 and Netty to 4.1.59.Final #225

carapace-server/src/main/java/org/carapaceproxy/server/RuntimeServerConfiguration.java, carapace-server/src/main/java/org/carapaceproxy/server/certificates/DynamicCertificatesManager.java, carapace-server/src/test/java/org/carapaceproxy/ConnectionPoolTest.java, carapace-server/src/test/java/org/carapaceproxy/server/certificates/DynamicCertificatesManagerTest.java
PR for #239 
Changelog:
- domain dns checking before acme certificates order creation
- _**dynamiccertificatesmanager.domainsreachabilitychecker.ipaddresses**_ to define carapace ips that acme certificate domains has to point to.
=> Perform dns check before create/renew certificate #239

carapace-server/src/main/java/org/carapaceproxy/server/RequestHandler.java, carapace-server/src/main/java/org/carapaceproxy/server/RuntimeServerConfiguration.java, carapace-server/src/main/java/org/carapaceproxy/server/cache/CacheRuntimeConfiguration.java, carapace-server/src/main/java/org/carapaceproxy/server/cache/ContentsCache.java, carapace-server/src/test/java/org/carapaceproxy/server/cache/CacheTest.java
PR for #260
Changelog:
- Https requests won't be cached anymore whether header _Cache-Control_ != _public_
- this is achieved only whether dynamic property **_cache.requests.secure.disablewithoutpublic = true_** is set
- Http/Https requests won't be cached anymore whether
- header _Pragma: no-cache_ is present
- header _Cache-Control_ has values: _private_, _no-cache_, _no-store_ or _max-age=0_
=> Manage cache mode in HTTPS requests #260

carapace-server/src/main/java/org/carapaceproxy/client/impl/ConnectionsManagerImpl.java, carapace-server/src/main/java/org/carapaceproxy/client/impl/EndpointConnectionImpl.java, carapace-server/src/main/java/org/carapaceproxy/server/ClientConnectionHandler.java, carapace-server/src/main/java/org/carapaceproxy/server/FullHttpMessageLogger.java, carapace-server/src/main/java/org/carapaceproxy/server/HttpProxyServer.java, carapace-server/src/main/java/org/carapaceproxy/server/Listeners.java, carapace-server/src/main/java/org/carapaceproxy/server/RuntimeServerConfiguration.java, carapace-server/src/test/java/org/carapaceproxy/server/FullHttpMessageLoggerTest.java, carapace-server/src/test/java/org/carapaceproxy/server/RequestsLoggerTest.java
Added an inbound handler to keep track of all clients requests and server responses and print them into dedicated logging file.
- New property _**accesslog.advanced.enabled=true**_ to enable advanged logging (default **false**)
- New property **_accesslog.advanced.body.size_** to limit the size of requests/responses body (default **1_000** bytes; 0 to disable)
All main configuration property values (like _file path_ and _timestamp format_) are inherited by **_accesslog._** ones.
Example of output:
```
<<<<<<<<<<<<<<<<<<<<[ CLIENT REQUEST (rid: 1) ]<<<<<<<<<<<<<<<<<<<<
Timestamp: 15-03-2021 10:11:01.140
HTTP Version: HTTP/1.1
HTTP Method: GET
URI: /index.html
--------------------[ HEADERS ]--------------------
Host: localhost
content-length: 0
<<<<<<<<<<<<<<<<<<<<[ CLIENT REQUEST END (rid: …
```
=> Dump request/resposte header and body in a file #262

carapace-server/pom.xml, pom.xml
AWS SDK updated from 2.13.13 to 2.16.18
Prometheus metrics updated from 4.12.0 to 4.13.0
Moreover, added Netty dependencies exclusion
=> Bump libs: awssdk and prometheus-metrics

.gitignore, carapace-server/src/main/java/org/carapaceproxy/server/certificates/DynamicCertificatesManager.java, carapace-server/src/test/java/org/carapaceproxy/server/certificates/DynamicCertificatesManagerTest.java
Regression from https://github.com/diennea/carapaceproxy/pull/257: certificates state is no more fetched from db but from cache, so during a certificate renewal this is outdated.
Changelog:
Now after every certificates batch update whether at least a certificate has been updated all cluster nodes reload cached data.
=> UI Certiticates list and detail > status outdated during renewal

carapace-server/src/main/java/org/carapaceproxy/client/impl/EndpointConnectionImpl.java, carapace-server/src/main/java/org/carapaceproxy/server/ClientConnectionHandler.java, carapace-server/src/main/java/org/carapaceproxy/server/FullHttpMessageLogger.java, carapace-server/src/main/java/org/carapaceproxy/server/Listeners.java
Whether the advanced logger is disabled we has not to call ctx.fireChannelRead
=> Advanced logger: disable fireChannelRead when disabled

carapace-server/src/main/java/org/carapaceproxy/api/CertificatesResource.java, carapace-server/src/main/java/org/carapaceproxy/configstore/CertificateData.java, carapace-server/src/main/java/org/carapaceproxy/server/certificates/DynamicCertificatesManager.java, carapace-server/src/main/java/org/carapaceproxy/utils/CertificatesUtils.java, carapace-server/src/test/java/org/carapaceproxy/api/StartAPIServerTest.java, carapace-server/src/test/java/org/carapaceproxy/server/certificates/CertificatesTest.java, carapace-server/src/test/java/org/carapaceproxy/server/certificates/CertificatesUtilsTest.java
Improved certificates data management on memory:
- serial number, expiring date and keystore data are now keep in memory and not more retrived from decoded chain
=> In-memory certificates data improvement

carapace-server/src/main/java/org/carapaceproxy/client/impl/EndpointConnectionImpl.java, carapace-server/src/main/java/org/carapaceproxy/server/Listeners.java, carapace-server/src/main/java/org/carapaceproxy/server/RequestHandler.java, carapace-server/src/test/java/org/carapaceproxy/RawClientTest.java
Changelog:
- whether the server send connection close now we close the channel to the client
- release connection to endpoint with forceClose flag now skip client check for release
- KeyManagerFactory is now wrapped by OpenSslCachingX509KeyManagerFactory (this should improve performance during ssl connections establishment)
=> Improved server-client connection release + ssl chain cache

carapace-server/src/main/java/org/carapaceproxy/client/impl/ConnectionsManagerImpl.java, carapace-server/src/main/java/org/carapaceproxy/client/impl/EndpointConnectionImpl.java, carapace-server/src/main/java/org/carapaceproxy/server/ClientConnectionHandler.java, carapace-server/src/main/java/org/carapaceproxy/server/RequestHandler.java, carapace-server/src/test/java/org/carapaceproxy/ConnectionPoolTest.java, carapace-server/src/test/java/org/carapaceproxy/RawClientTest.java, carapace-server/src/test/java/org/carapaceproxy/backends/ChunkedEncodingResponseTest.java, carapace-server/src/test/java/org/carapaceproxy/backends/RestartEndpointTest.java, carapace-server/src/test/java/org/carapaceproxy/server/mapper/requestmatcher/RequestMatcherTest.java
- Improved connections exclusively reuse
- Endpoints connections released right after clients one is closed (client-endpoint release handshake dropped)
- Requests form same client (re)uses same endpoint connection
- Clients endpoint-connection reuse reset on config reload and endpoint down
=> Improve client-endpoints connection management

carapace-server/src/main/java/org/carapaceproxy/EndpointStats.java, carapace-server/src/main/java/org/carapaceproxy/api/BackendsResource.java, carapace-server/src/main/java/org/carapaceproxy/core/HttpProxyServer.java, carapace-server/src/main/java/org/carapaceproxy/core/Listeners.java, carapace-server/src/main/java/org/carapaceproxy/core/ProxyRequestsManager.java, carapace-server/src/main/java/org/carapaceproxy/core/RuntimeServerConfiguration.java, carapace-server/src/main/java/org/carapaceproxy/server/config/ConnectionPoolConfiguration.java, carapace-server/src/test/java/org/carapaceproxy/backends/ConnectionPoolTest.java
PR for #307
Now it's possible to define connection pools via dynamic configuration:
```
connectionpool.1.id = myconnectionpoolid # required, unique
connectionpool.1.domain = mydomain # regexp used to choose the pool to use (required)
connectionpool.1.maxconnectionsperendpoint = 50 # like connectionsmanager.maxconnectionsperendpoint (= default)
connectionpool.1.borrowtimeout = 60000 # like connectionsmanager.borrowtimeout (= default)
connectionpool.1.connecttimeout = 10000 # like connectionsmanager.connecttimeout (= default)
connectionpool.1.stuckrequesttimeout = 300000 # like connectionsmanager.stuckrequesttimeout (= default)
connectionpool.1.idletimeout = 300000 # like connectionsmanager.idletimeout (= default)
connectionpool.1.enabled = true | false # default = false
```
A default …
=> Domain dedicated connection pool management #307

carapace-server/src/main/java/org/carapaceproxy/server/cache/ContentsCache.java
Changelod:
- fix to direct memory leak in cache actions
Problem:
Calling copy.retain() increases the object's refCnt to 2. This disables the cleaner.
Calling release() only decrements the refCnt to 1. But the object is deallocated only if the refCnt is at 0.
With retainedDuplicated() the refCnt at the release point is at 1, so calling release() the object is deallocated.
=> Fix direct memory leaks

carapace-server/src/main/java/org/carapaceproxy/core/HttpProxyServer.java, carapace-server/src/main/java/org/carapaceproxy/core/ProxyRequestsManager.java
Fix to connections pool reload even without connection/backends configuration changes
Fix connections pools metrics not updated after configuration reload
=> Fix connection pool reload and metrics

carapace-server/src/main/java/org/carapaceproxy/core/ProxyRequestsManager.java
In order to avoid proxy-to-server-clients setup at every proxy request now we use an existent client from a pool configured by endpoint-connectionpool.
=> Improving requests forwarding

carapace-ui/src/main/webapp/package.json, carapace-ui/src/main/webapp/yarn.lock
Dependabot reported vulnerability in the version of scss-tokenizer used.
Considering it is a node-sass dependency, we have updated node-sass to the latest version.
=> Fix dependabot alert

carapace-server/src/main/java/org/carapaceproxy/SimpleHTTPResponse.java, carapace-server/src/main/java/org/carapaceproxy/api/ConfigResource.java, carapace-server/src/main/java/org/carapaceproxy/api/RoutesResource.java, carapace-server/src/main/java/org/carapaceproxy/core/HttpProxyServer.java, carapace-server/src/main/java/org/carapaceproxy/core/ProxyRequestsManager.java, carapace-server/src/main/java/org/carapaceproxy/core/RuntimeServerConfiguration.java, carapace-server/src/main/java/org/carapaceproxy/core/StaticContentsManager.java, carapace-server/src/main/java/org/carapaceproxy/server/config/RouteConfiguration.java, carapace-server/src/main/java/org/carapaceproxy/server/mapper/EndpointMapper.java, carapace-server/src/main/java/org/carapaceproxy/server/mapper/MapResult.java, carapace-server/src/main/java/org/carapaceproxy/server/mapper/StandardEndpointMapper.java, carapace-server/src/main/resources/default-error-pages/500_maintenance.html, carapace-server/src/test/java/org/carapaceproxy/MaintenanceModeTest.java, carapace-ui/src/main/webapp/src/components/Configuration.vue, carapace-ui/src/main/webapp/src/components/Navbar.vue, carapace-ui/src/main/webapp/src/components/Routes.vue, carapace-ui/src/main/webapp/src/variables.scss
- provide dynamic config - **carapace.maintenancemode.enabled=true/false**
- added possibility of configuring a maintenance page per route (ex. **route.1.maintenanceaction=maintenance-static-action**)
=> Carapace > Provide maintenance mode

carapace-server/src/main/java/org/carapaceproxy/core/ProxyRequestsManager.java, carapace-server/src/main/java/org/carapaceproxy/core/RuntimeServerConfiguration.java, carapace-server/src/test/java/org/carapaceproxy/backends/ChunkedEncodingResponseTest.java
Since HTTP 1.0 clients aren't required to support chunked transfer encoding, it shouldn't be used upon responding to HTTP/1.0 requests. Otherwise, a non-supporting client would just ignore the encoding and deliver a messed up response body to the application layer.
Implementation:
provide a dynamic configuration to enable or disabile this fix:
**carapace.http10backwardcompatibility.enabled=true/false** (default false)
More info:
[Writing data reactor netty](https://projectreactor.io/docs/netty/release/reference/index.html#_writing_data_4)
[Reactor netty set content lenght automatically](https://stackoverflow.com/questions/57802358/netty-set-content-length-automatically)
=> Avoid using chunked transfer encoding while replying to HTTP/1.0 requests

carapace-server/src/main/java/org/carapaceproxy/api/CertificatesResource.java, carapace-server/src/main/java/org/carapaceproxy/api/ConfigResource.java, carapace-server/src/main/java/org/carapaceproxy/api/SimpleResponse.java, carapace-server/src/main/java/org/carapaceproxy/cluster/GroupMembershipHandler.java, carapace-server/src/main/java/org/carapaceproxy/cluster/impl/NullGroupMembershipHandler.java, carapace-server/src/main/java/org/carapaceproxy/cluster/impl/ZooKeeperGroupMembershipHandler.java, carapace-server/src/main/java/org/carapaceproxy/configstore/CertificateData.java, carapace-server/src/main/java/org/carapaceproxy/configstore/HerdDBConfigurationStore.java, carapace-server/src/main/java/org/carapaceproxy/core/HttpProxyServer.java, carapace-server/src/main/java/org/carapaceproxy/core/RuntimeServerConfiguration.java, carapace-server/src/main/java/org/carapaceproxy/server/certificates/DynamicCertificatesManager.java, carapace-server/src/test/java/org/carapaceproxy/api/StartAPIServerTest.java, carapace-server/src/test/java/org/carapaceproxy/cluster/impl/ZooKeeperGroupMembershipHandlerTest.java, carapace-server/src/test/java/org/carapaceproxy/cluster/impl/ZookKeeperACLTest.java, carapace-server/src/test/java/org/carapaceproxy/configstore/ConfigurationStoreTest.java, carapace-server/src/test/java/org/carapaceproxy/server/certificates/CertificatesTest.java, carapace-server/src/test/java/org/carapaceproxy/server/certificates/DynamicCertificatesManagerTest.java, carapace-server/src/test/java/org/carapaceproxy/utils/CertificatesTestUtils.java, carapace-ui/src/main/webapp/src/components/CacheStatus.vue, carapace-ui/src/main/webapp/src/components/Certificate.vue, carapace-ui/src/main/webapp/src/components/CertificatesStatus.vue, carapace-ui/src/main/webapp/src/components/Configuration.vue, carapace-ui/src/main/webapp/src/components/Navbar.vue, carapace-ui/src/main/webapp/src/components/Sidebar.vue
Addes these dynamic props:
- dynamiccertificatesmanager.localcertificates.store.path: to enable the local store of acme certificates to specified path
- dynamiccertificatesmanager.localcertificates.peers.ids: to enable the local store for specific peers (default is enabled for all pees)
All acme certificates are dumped in local storage when became  AVAILABLE or when forced from admin (by dumping a specified cert or all of them).
Added support to attach data to zookeeper events.
Also, the column privateKey of digital_certificates table has been dropped.
Finally a fix to maintenance mode , buttons and sidebar styles
=> Certificate > sync certificates locally #324

carapace-server/src/main/java/org/carapaceproxy/core/ProxyRequestsManager.java, carapace-server/src/test/java/org/carapaceproxy/backends/ChunkedEncodingResponseTest.java, carapace-server/src/test/java/org/carapaceproxy/server/mapper/BasicStandardEndpointMapperTest.java, pom.xml
* update WireMock
* fix `org.carapaceproxy.backends.ChunkedEncodingResponseTest`
* fix `org.carapaceproxy.server.mapper.BasicStandardEndpointMapperTest`
This fixes #397
=> Fix failing tests

carapace-server/src/main/java/org/carapaceproxy/core/RequestsLogger.java, carapace-server/src/main/java/org/carapaceproxy/core/RuntimeServerConfiguration.java
* cache a `SimpleDateFormatter` in configuration
* inject the formatter instead of the pattern when building `Entries`
Fixes #394
=> Inject timestamp formatter in Entry instead of a pattern

carapace-server/src/main/java/org/carapaceproxy/api/ConnectionPoolsResource.java, carapace-server/src/main/java/org/carapaceproxy/core/Listeners.java, carapace-server/src/main/java/org/carapaceproxy/core/ProxyRequestsManager.java, carapace-server/src/main/java/org/carapaceproxy/core/RuntimeServerConfiguration.java, carapace-server/src/main/java/org/carapaceproxy/server/config/ConnectionPoolConfiguration.java, carapace-server/src/main/java/org/carapaceproxy/server/config/NetworkListenerConfiguration.java, carapace-server/src/test/java/org/carapaceproxy/RawClientTest.java, carapace-server/src/test/java/org/carapaceproxy/SimpleHTTPProxyTest.java, carapace-server/src/test/java/org/carapaceproxy/backends/ConnectionPoolTest.java, carapace-server/src/test/java/org/carapaceproxy/listeners/ListenerConfigurationTest.java, carapace-server/src/test/java/org/carapaceproxy/listeners/SSLSNITest.java, carapace-server/src/test/java/org/carapaceproxy/server/cache/CacheTest.java, carapace-server/src/test/java/org/carapaceproxy/server/filters/XTlsCipherFilterTest.java, carapace-server/src/test/java/org/carapaceproxy/server/filters/XTlsProtocolFilterTest.java
#415 
EpollEventLoopGroup vs. NioEventLoopGroupand in high load scenarios could provide better performance in:
- CPU usage
- Memory usage
- Allocations
It would be good to include the ability to switch to EpollEventLoopGroup if the operating system supports it.
=> Use Epol EpollEventLoopGroup if supported by OS

carapace-server/src/main/java/org/carapaceproxy/SimpleHTTPResponse.java, carapace-server/src/main/java/org/carapaceproxy/core/ProxyRequest.java, carapace-server/src/main/java/org/carapaceproxy/core/ProxyRequestsManager.java, carapace-server/src/main/java/org/carapaceproxy/core/StaticContentsManager.java, carapace-server/src/main/java/org/carapaceproxy/server/config/RouteConfiguration.java, carapace-server/src/main/java/org/carapaceproxy/server/mapper/EndpointMapper.java, carapace-server/src/main/java/org/carapaceproxy/server/mapper/MapResult.java, carapace-server/src/main/java/org/carapaceproxy/server/mapper/StandardEndpointMapper.java, carapace-server/src/main/resources/default-error-pages/400_badrequest.html, carapace-server/src/test/java/org/carapaceproxy/backends/ConnectionPoolTest.java, pom.xml
#412
As per RFC, if host header is missing or wrong the response must be 400 Bad request.
See https://www.rfc-editor.org/rfc/rfc2616#page-38
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host
the error page can be customized by setting:
`default.action.badrequest=custom_action`
=> NullPointerException when http header host is null

carapace-server/src/main/java/org/carapaceproxy/SimpleHTTPResponse.java, carapace-server/src/main/java/org/carapaceproxy/core/ProxyRequestsManager.java, carapace-server/src/main/java/org/carapaceproxy/core/StaticContentsManager.java, carapace-server/src/main/java/org/carapaceproxy/server/mapper/EndpointMapper.java, carapace-server/src/main/java/org/carapaceproxy/server/mapper/MapResult.java, carapace-server/src/main/java/org/carapaceproxy/server/mapper/StandardEndpointMapper.java, carapace-server/src/main/resources/default-error-pages/503_serviceunavailable.html, carapace-server/src/test/java/org/carapaceproxy/RawClientTest.java, carapace-server/src/test/java/org/carapaceproxy/SimpleHTTPProxyTest.java, carapace-server/src/test/java/org/carapaceproxy/backends/RestartEndpointTest.java, carapace-server/src/test/java/org/carapaceproxy/backends/UnreachableBackendTest.java
In the current implementation, in case of problems during a request from Carapace to the server, we return the error page `"500 An internal error occured" ` via the `Publisher<Void> serveServiceNotAvailable(ProxyRequest request) `function.
The error page returned is the default one and cannot be customized.
Changes:
- In case of problems, the default error code` 503 service unavailable` is returned
- Added dynamic sys prop **default.action.serviceunavailable** to set up your own custom error page
=> Service unavailable page customization

.github/workflows/pr-validation-report.yml, .github/workflows/pr-validation.yml
Splitting PR validation workflow in two, one doing the actual validation, and the other publishing checks with the right permissions
See:
* https://github.com/marketplace/actions/junit-report-action#pr-run-permissions
* https://github.com/marketplace/actions/publish-test-results#permissions
* https://github.com/marketplace/actions/test-reporter#recommended-setup-for-public-repositories
=> Fix PR validation permissions by splitting in two workflows

carapace-server/pom.xml, carapace-ui/pom.xml, pom.xml
upgrade was needed to support building on JDK21 (closes #470)
=> build(server): upgrade Lombok to 1.18.32

.github/workflows/pr-validation-report.yml, .github/workflows/pr-validation.yml, .mvn/wrapper/MavenWrapperDownloader.java, .mvn/wrapper/maven-wrapper.properties, carapace-server/pom.xml, carapace-server/src/main/java/org/carapaceproxy/api/ConfigResource.java, carapace-server/src/main/java/org/carapaceproxy/api/ConnectionPoolsResource.java, carapace-server/src/main/java/org/carapaceproxy/api/response/FormValidationResponse.java, carapace-server/src/main/java/org/carapaceproxy/client/EndpointKey.java, carapace-server/src/main/java/org/carapaceproxy/configstore/ConfigurationConsumer.java, carapace-server/src/main/java/org/carapaceproxy/configstore/ConfigurationStore.java, carapace-server/src/main/java/org/carapaceproxy/configstore/HerdDBConfigurationStore.java, carapace-server/src/main/java/org/carapaceproxy/configstore/PropertiesConfigurationStore.java, carapace-server/src/main/java/org/carapaceproxy/core/HttpProxyServer.java, carapace-server/src/main/java/org/carapaceproxy/core/ProxyRequestsManager.java, carapace-server/src/main/java/org/carapaceproxy/core/RuntimeServerConfiguration.java, carapace-server/src/test/java/org/carapaceproxy/api/ClusterReconfigTest.java, carapace-server/src/test/java/org/carapaceproxy/api/ConnectionPoolsResourceTest.java, carapace-server/src/test/java/org/carapaceproxy/utils/RawHttpClient.java, carapace-ui/pom.xml, mvnw, mvnw.cmd
See #419 
During the CI pipeline, I experienced some problems between Java 21 and the version of the `maven-compiler-plugin` bundled with the version of maven provided with the GitHub Actions.
To pin a specific version of Maven, I decided to introduce the [wrapper](https://maven.apache.org/wrapper): like Gradle, it introduces a couple of shell scripts (plus a Java one) that handle the download and the execution of a specific version of the build system, in fact making it another dependency of the project.
This is good to control better how the build is done, both in CI and in development.
- Java version was updated to Java 21
- Now using Maven wrapper instead of Maven directly
- Updated dorny/test-reporter action to version v1.9.1, that allows to use v4 of actions/upload-artifact and …
=> Implement CRUD APIs for connection pools

carapace-server/src/main/java/org/carapaceproxy/api/CertificatesResource.java, carapace-server/src/main/java/org/carapaceproxy/configstore/ConfigurationStore.java, carapace-server/src/main/java/org/carapaceproxy/configstore/HerdDBConfigurationStore.java, carapace-server/src/main/java/org/carapaceproxy/configstore/PropertiesConfigurationStore.java, carapace-server/src/test/java/org/carapaceproxy/server/certificates/CertificatesTest.java
=> feat(server): add DELETE API for Carapace certificates

carapace-server/pom.xml, carapace-server/src/main/java/org/carapaceproxy/api/RequestFiltersResource.java, carapace-server/src/main/java/org/carapaceproxy/core/ForwardedStrategies.java, carapace-server/src/main/java/org/carapaceproxy/core/ForwardedStrategy.java, carapace-server/src/main/java/org/carapaceproxy/core/Listeners.java, carapace-server/src/main/java/org/carapaceproxy/core/RuntimeServerConfiguration.java, carapace-server/src/main/java/org/carapaceproxy/server/config/NetworkListenerConfiguration.java, carapace-server/src/main/java/org/carapaceproxy/server/filters/RequestFilterFactory.java, carapace-server/src/main/java/org/carapaceproxy/server/filters/XForwardedForRequestFilter.java, carapace-server/src/test/java/org/carapaceproxy/ApplyConfigurationTest.java, carapace-server/src/test/java/org/carapaceproxy/DatabaseConfigurationTest.java, carapace-server/src/test/java/org/carapaceproxy/RawClientTest.java, carapace-server/src/test/java/org/carapaceproxy/SimpleHTTPProxyTest.java, carapace-server/src/test/java/org/carapaceproxy/api/StartAPIServerTest.java, carapace-server/src/test/java/org/carapaceproxy/core/ForwardedStrategyTest.java, carapace-server/src/test/java/org/carapaceproxy/listeners/ListenerConfigurationTest.java, carapace-server/src/test/java/org/carapaceproxy/listeners/SSLSNITest.java, carapace-server/src/test/java/org/carapaceproxy/server/cache/CacheTest.java, carapace-server/src/test/java/org/carapaceproxy/server/filters/XForwardedForFilterTest.java, carapace-server/src/test/java/org/carapaceproxy/server/filters/XTlsCipherFilterTest.java, carapace-server/src/test/java/org/carapaceproxy/server/filters/XTlsProtocolFilterTest.java, carapace-server/src/test/java/org/carapaceproxy/utils/RawHttpClient.java, carapace-server/src/test/java/org/carapaceproxy/utils/TestEndpointMapper.java, pom.xml
- Add [Apache `commons-net:commons-net:3.11.0`](https://commons.apache.org/proper/commons-net/) dependency
- Move [`X-Forwarded-For` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For) management from `add-x-forwarded-for` filter to new listener options:
- `add-x-forwarded-for` filter is now deprecated for removal
- added `forwarded` = `DROP` | `PRESERVE` | `REWRITE` (default) | `IF_TRUSTED` listener option
- added `trustedips` optional listener option, that accepts CIDR that should be considered trusted
=> feat(server): Trust `X-Forwarded-For` header for some IPs

carapace-server/src/main/java/org/carapaceproxy/core/ForwardedStrategies.java, carapace-server/src/test/java/org/carapaceproxy/core/ForwardedStrategyTest.java
Follow-up of #477, closes #492
=> fix(server): add default identifier if not specified by the user

.mvn/wrapper/maven-wrapper.properties, carapace-server/pom.xml, carapace-server/src/main/java/org/carapaceproxy/server/certificates/ACMEClient.java, carapace-server/src/test/java/org/carapaceproxy/RawClientTest.java, carapace-ui/pom.xml, pom.xml
Closes #476 
* upgrade [Maven Wrapper](https://maven.apache.org/wrapper/) to Maven **3.9.9**;
* add [Reactor Tools](https://projectreactor.io/docs/core/release/reference/index.html#reactor-tools-debug) to improve debug capabilities;
* upgrade [Reactor Netty BOM](https://projectreactor.io/docs/netty/release/reference/index.html#getting) to version **2023.0.11**; 
- this bumps Project Reactor dependencies to **3.6.11**
- this bumps Reactor Netty dependencies to **1.1.23**;
* use [Netty BOM](https://github.com/netty/netty/issues/5994) to ensure that Netty-related dependencies outside of Reactor Netty BOM are aligned to version **4.1.114.Final**;
- this includes [`io.netty:netty-tcnative-boringssl-static`](https://netty.io/wiki/forked-tomcat-native.html), now on version **2.0.66.Final**;
* …
=> Converge dependency versions

carapace-server/src/main/java/org/carapaceproxy/configstore/HerdDBConfigurationStore.java, carapace-server/src/main/java/org/carapaceproxy/server/backends/BackendHealthCheck.java, carapace-server/src/test/java/org/carapaceproxy/ApplyConfigurationTest.java, carapace-server/src/test/java/org/carapaceproxy/BigUploadTest.java, carapace-server/src/test/java/org/carapaceproxy/ConcurrentClientsTest.java, carapace-server/src/test/java/org/carapaceproxy/SimpleHTTPProxyTest.java, carapace-server/src/test/java/org/carapaceproxy/backends/RestartEndpointTest.java, carapace-server/src/test/java/org/carapaceproxy/configstore/ConfigurationStoreTest.java, carapace-server/src/test/java/org/carapaceproxy/core/JettyHttpTraceMethodTest.java, carapace-server/src/test/java/org/carapaceproxy/listeners/MultiListeningEndpointTest.java, carapace-server/src/test/java/org/carapaceproxy/server/certificates/CertificatesTest.java, carapace-server/src/test/java/org/carapaceproxy/server/certificates/DynamicCertificatesManagerTest.java, carapace-server/src/test/java/org/carapaceproxy/server/mapper/BasicStandardEndpointMapperTest.java, carapace-server/src/test/java/org/carapaceproxy/server/mapper/ForceBackendTest.java, carapace-server/src/test/java/org/carapaceproxy/utils/HttpTestUtils.java
`new URL` constructor is deprecated since Java 20: <https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/net/URL.html>
closes #509
=> feat: fix URL deprecation warnings

carapace-server/pom.xml
When running on macOS with an ARM-based device, we get the following warning:
```
nov 04, 2024 11:46:57 AM io.netty.resolver.dns.DnsServerAddressStreamProviders <clinit>
GRAVE: Unable to load io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS. Check whether you have a dependency on 'io.netty:netty-resolver-dns-native-macos'. Use DEBUG level to see the full stack: java.lang.UnsatisfiedLinkError: failed to load the required native library
This is because Netty requires io.netty:netty-resolver-dns-native-macos in the classpath to leverage DNS resolution correctly.
```
Reactor Netty bundles the x86 version, but not the ARM one
=> build: add MacOS native DNS bindings for ARM

carapace-server/src/test/java/org/carapaceproxy/core/Http2HeadersTest.java, pom.xml
Upgrade Reactor Netty to 1.1.24; needed for #410 
* see reactor/reactor-netty#3473
* see reactor/reactor-netty#3475
=> build: upgrade Reactor BOM to 2023.0.12

carapace-server/src/main/assemble/zip-assembly.xml, carapace-server/src/main/java/org/carapaceproxy/launcher/ServerMain.java, carapace-server/src/main/resources/bin/setenv.sh, run.sh
`run.sh` could not start server anymore:
```
2025-01-22 18:03:49 [main] ERROR o.carapaceproxy.launcher.ServerMain - Error while starting server
java.io.FileNotFoundException: conf/logging.properties (No such file or directory)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:106)
at java.logging/java.util.logging.LogManager.readConfiguration(LogManager.java:1383)
at org.carapaceproxy.launcher.ServerMain.main(ServerMain.java:109)
```
Also, it showed an undesired warning if the service is not there for some reason, i.e. after a fresh clone, or a clean, or a version bump:
```bash
❯ …
```
=> Fix regression after switching from JUL to Logback

pom.xml
Following the wave of #538 and #539, I'm upgrading Netty, Reactor Netty and Eclipse Jetty also on `master`, as @hamadodene requested.
Differently from what was done on hotfix releases on `release/2.0` and `release/2.1`, I'm bumping it straight to latest version.
I also dropped a couple of Maven repositories hoping to speed up a painfully slow release process
=> Upgrade Netty

carapace-server/pom.xml, carapace-server/src/main/java/org/carapaceproxy/core/ProxyRequestsManager.java, carapace-server/src/main/java/org/carapaceproxy/server/config/BackendConfiguration.java, carapace-server/src/main/java/org/carapaceproxy/server/mapper/MapResult.java, carapace-server/src/main/java/org/carapaceproxy/server/mapper/StandardEndpointMapper.java, carapace-server/src/main/resources/conf/server.dynamic.properties, carapace-server/src/test/java/org/carapaceproxy/backends/SSLBackendTest.java, carapace-ui/pom.xml, pom.xml
This PR introduces support for forwarding HTTP requests to backend servers in secure (SSL/TLS) mode in Carapace Proxy. The changes allow the proxy to connect to HTTPS backends, with custom CA certificate support, improving flexibility and security for enterprise deployments.
- **Backend SSL Support:** 
-  `backend.<n>.ssl=true`: configure backend servers to use SSL/TLS for secure connections.
- **Custom Certificate Authority (CA) Support:** (optional)
- `backend.<n>.cacertificate`: specify custom CA certificates for backend SSL validation.
- `backend.<n>.cacertificatepassword`: support for CA certificate password in configuration.
Previously, Carapace Proxy was unable to forward requests to backend servers using secure (HTTPS) connections. This limitation caused failures when attempting …
=> 530 carapace http client is unable to forward requests in secure mode

carapace-server/src/main/java/org/carapaceproxy/core/ListeningChannel.java, carapace-server/src/main/java/org/carapaceproxy/core/ProxyRequestsManager.java, carapace-server/src/main/java/org/carapaceproxy/server/mapper/MapResult.java, carapace-server/src/main/java/org/carapaceproxy/utils/AlpnUtils.java, carapace-server/src/main/java/org/carapaceproxy/utils/HttpUtils.java, carapace-server/src/test/java/org/carapaceproxy/backends/SSLBackendTest.java, carapace-server/src/test/java/org/carapaceproxy/core/HttpProtocolAndSSLTest.java
Fixes #529
The Carapace Proxy was not accepting HTTP/2 connections despite being configured for H2, with debug logs showing `ALPN, server did not agree to a protocol`. This resulted in HTTP/2 framing layer errors and connection failures.
The server was not advertising HTTP/2 protocol support during SSL handshake.
=> Listener does not accept HTTP/2 connections even though HTTP/2 is enabled
